"""
Generate the C++ tables of the plugin from the Labium Phase 1 data.

  src/dsp/KcalTable.inc   tuning calibration k_cal per key (Phase 1 calibrate.py)
  tests/RefData.inc       Phase 1 reference metrics used by tests/labium_check.cpp

Input: the Phase 2 bundle OkumuLab1/data/step1_data.js (it carries the Phase 1
kcal table, the one-period states, the wind attacks and the range analysis).

    python tools/gen_tables.py ../OkumuLab1/data/step1_data.js
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def load(path):
    s = open(path, encoding='utf8').read()
    return json.loads(s[s.index('{'):s.rindex('}') + 1])


def fmt(x):
    if x is None or (isinstance(x, float) and x != x):
        return 'NAN_'
    return repr(float(x))


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, '..', 'OkumuLab1', 'data', 'step1_data.js')
    d = load(src)

    kc = d['kcal']
    keys = sorted(int(k) for k in kc)
    with open(os.path.join(ROOT, 'src', 'dsp', 'KcalTable.inc'), 'w', encoding='utf8') as f:
        f.write('// generated by tools/gen_tables.py from the Labium Phase 1 kcal.json (do not edit)\n')
        f.write('static constexpr int kKcalFirst = %d, kKcalCount = %d;\n' % (keys[0], len(keys)))
        f.write('static constexpr double kKcal[kKcalCount] = {\n')
        for k in keys:
            v = kc[str(k)]
            v = v['k_cal'] if isinstance(v, dict) else v
            f.write('    %s,  // %d\n' % (repr(float(v)), k))
        f.write('};\n')

    with open(os.path.join(ROOT, 'tests', 'RefData.inc'), 'w', encoding='utf8') as f:
        f.write('// generated by tools/gen_tables.py from the Labium Phase 1 analysis (do not edit)\n')
        f.write('#define NAN_ std::numeric_limits<double>::quiet_NaN()\n')
        f.write('struct RefState { const char* name; int midi; double f, regime, db; double hm[12]; };\n')
        f.write('static const RefState kRefStates[] = {\n')
        for name, v in d['vis'].items():
            hm = (list(v.get('harmonics_db') or []) + [None] * 12)[:12]
            f.write('    {"%s", %d, %s, %s, %s, {%s}},\n' % (name, v['midi'], fmt(v['f_sounding']), fmt(v['regime']),
                                                     fmt(v['level_db']), ', '.join(fmt(x) for x in hm)))
        f.write('};\n')
        f.write('struct RefWind { double pMMWS, f, regime, db; };\n')
        f.write('static const RefWind kRefWind[] = {\n')
        for w in d['windAttacks']:
            f.write('    {%s, %s, %s, %s},\n' % (fmt(w['p_mmws']), fmt(w['f']), fmt(w['regime']), fmt(w['db'])))
        f.write('};\n')
        f.write('struct RefRange { int midi; double f0, f, db; double hm[12]; };\n')
        f.write('static const RefRange kRefRange[] = {\n')
        for r in d['range']:
            hm = (list(r.get('hm') or []) + [None] * 12)[:12]
            f.write('    {%d, %s, %s, %s, {%s}},\n' % (r['midi'], fmt(r['f0']), fmt(r['f']), fmt(r['db']), ', '.join(fmt(x) for x in hm)))
        f.write('};\n')
    print('kcal keys %d..%d, %d states, %d wind attacks, %d range keys' % (keys[0], keys[-1], len(d['vis']), len(d['windAttacks']), len(d['range'])))


if __name__ == '__main__':
    main()
